### ISSUE TITLE
Distribucia

### ISSUE THREAD

**Issue by durasj** [slovensko-digital/autogram#12]
Pain point desktop aplikacii je distribucia. #5 rozprava o distribucii updatov, ale chybaju este rozhodnutia o prvotnej distribucii.

V mojej verzii a kostre je spravene balenie do .zip pre vsetky 3 platformy a mam nacrtnute aj zaregistrovanie custom protokolu - na Windowse je to sucast .exe launchera, ktory pri spusteni overi ci su spravne nastevene veci v registri, ostatne platformy uz menej automatizovane. To znamena, ze momentalne na mojej strane to mam ako nepodpisanu "portable" aplikaciu.

Predpokladam ale, ze budete chciet:

1. Spravit installer/klasicke packages pre danu platformu - t.j. .exe installer pre Window, .dmg pre macOS, .AppImage/.deb/.rpm pre Linux.
2. Podpisat appku na Windowse a macOS - toto je super dolezite! Inak to bezny clovek nespusti. Na macOS staci Apple Developer - je potrebne tu zabalenu appku podpisat a notarizovat (nechat prejst cez ich servery so spravne vyplnenym .plist om a drsnejsimi security pravidlami na appke - Octosign tym prechadza, takze by nemal byt problem). Na Windowse je to horsie, idealne je podpisane cez Extended Validation code signing cert. Inak to bude davat vela false positives - Windows to nebude chciet spustit, rozne antiviraky to budu davat do karanteny etc. EV CSC je ale prakticky vzdy hardvery token, takze ak to chcete mat von pre ludi v dohladnej dobe tak by to bolo fajn zacat riesit. Naposledy som ho kupoval cez Microsoft s nejakou zlavou 50%, takze to stalo "len" nejakych 500E rocne.

Planuje sa pridavanie do obchodov/repozitarov?

@jsuchal Feel free dat tomu spravnu prioritu (milestone).

**Comment by jsuchal** [comment]
Tu vyzera byt nejaky github action https://github.com/sudara/pamplejuce/blob/main/.github/workflows/cmake_ctest.yml
