### ISSUE TITLE
Bundling with JRE

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#131]
Vyzera, ze bundlujeme JDK, co asi nie je potrebne a je tak 2.5x vacsie ako by mohlo byt, keby sme bundlovali JRE. Javisti, viete toto kuknut, ze ako to spravit, aby to pre release pouzivalo JRE?

**Comment by jsuchal** [comment]
@sabomichal tuto este mame nejaky napad co dalej alebo zatvorime issue?

**Comment by sabomichal** [comment]
@1azyman chcel este kontrolovat ci su vsetky moduly potrebne, tak neviem..

**Comment by jsuchal** [comment]
Uz netreba nic.
