### ISSUE TITLE
MacOS: Nahlad na vysoky dokument zamedzuje podpisaniu

### ISSUE THREAD

**Issue by kiblik** [slovensko-digital/autogram#172]
Nahladove okno je privysoke a nakolko nie je scroll-ovatelne, zamedzuje pristupu k podpisovemu tlacidlu.

Ukazka:
![image](https://user-images.githubusercontent.com/5609770/236338894-4f838e4d-62fc-4f49-b49a-1c714e481454.png)

MacOS: 13.3.1
Autogram: 1.99.9

**Comment by kiblik** [comment]
> Toto je pre PDF, ze?

Nie, PNG

**Comment by jsuchal** [comment]
@kiblik toto je zvlastne, neviem to zreplikovat (som ale linux). Ake mas rozlisenie? Vies mi hodit cely screen a pripadne to png?

**Comment by jsuchal** [comment]
@kiblik pre pdf alebo textove subory ti to robi to iste ci nie?

**Comment by kiblik** [comment]
> @kiblik pre pdf alebo textove subory ti to robi to iste ci nie?

Subory bez nahladu su v pohode

<img width="616" alt="Screenshot 2023-05-07 at 09 40 00" src="https://user-images.githubusercontent.com/5609770/236670030-d045a8c2-7253-4933-9e7c-d032bf40c473.png">

Plaintext je tiez v pohode

<img width="612" alt="Screenshot 2023-05-07 at 09 43 29" src="https://user-images.githubusercontent.com/5609770/236670052-9bda47f5-e8ff-47a6-8af4-990ff3c9c5ea.png">

PDF:
- Na rozdiel od obrazku, scrollovatko dokumentu je pre PDF k dispozicii hned
- Podpisove tlacidlo je vsak mimo viditelnu zonu

<img width="622" alt="Screenshot 2023-05-07 at 09 38 20" src="https://user-images.githubusercontent.com/5609770/236670078-c303dc78-ac85-43fb-83fe-c84b912169ca.png">

Po resize okna uz v pohode

<img width="619" alt="Screenshot 2023-05-07 at 09 34 58" src="https://user-images.githubusercontent.com/5609770/236670091-f7a8edf4-74f6-4e3b-8719-45d91c86853c.png">

**Comment by jsuchal** [comment]
Ale máš rozlíšenie?

**Comment by kiblik** [comment]
> Ale máš rozlíšenie?

Display ma 2560 × 1600, ale ja bezim na 1440 × 900 (default)

<img width="462" alt="image" src="https://user-images.githubusercontent.com/5609770/236676980-0e0ceac6-78b9-41fd-81f4-742378057abb.png">

Pri "more space (2560 × 1600)"
- je stale problem s vysokym obrazkom
- PDF je OK

**Comment by jsuchal** [comment]
Skusil som u seba extra male rozlisenie (700px na vysku), na linuxe vsetko ok. Overim este Windows a potom asi musim vyhrabat nejaky mac (zmurk @crutch) lebo neviem zreplikovat.
