### ISSUE TITLE
Chybna detegcia poslednej verzie

### ISSUE THREAD

**Issue by kiblik** [slovensko-digital/autogram#173]
Napriek tomu, ze som nainstaloval Autogram z https://github.com/slovensko-digital/autogram/releases/latest, hned pri prvom starte mi hlasil, ze na GH je aktualnejsia verzia.

![image](https://user-images.githubusercontent.com/5609770/236339475-cd294fba-72f2-4403-89d8-31c538d21231.png)

MacOS: 13.3.1
Autogram: 1.99.9

**Comment by jsuchal** [comment]
@celuchmarek vies kuknut?

**Comment by celuchmarek** [comment]
Jo. Mám podozrenie, že to bude tým "v" na začiatku tagu .

**Comment by jsuchal** [comment]
@celuchmarek jo to bude asi ono.

**Comment by jsuchal** [comment]
uz smerujeme na spravny tag ale stale to hadze ten update.

**Comment by jsuchal** [comment]
Vyzera to tak, ze nas manifest neobsahuje meno package `Name: ` a teda toto vlastne nemoze uplne fungovat. Neviem to tam uplne dostat. 

@1azyman @sabomichal ?

**Comment by kiblik** [comment]
Videl som, ze na urcitenie verzie sa pouziva citanie headeru z redirectu pri pristupe na
https://github.com/slovensko-digital/autogram/blob/ab47e24c63359443358c7559d64d3abe12d30927/src/main/java/digital/slovensko/autogram/core/Updater.java#L14

Nebolo by lepsie vyuzit API?
```bash
$ curl https://api.github.com/repos/slovensko-digital/autogram/releases/latest 2>/dev/null | jq '.tag_name'
"1.99.9"
$ curl https://api.github.com/repos/slovensko-digital/autogram/releases/latest 2>/dev/null | jq '.name'
"v1.99.9"
```

**Comment by jsuchal** [comment]
Vyzera, ze najlahsie to bude proste cez toto https://stackoverflow.com/questions/66759345/simplest-way-to-query-cfg-file-created-by-jpackage

`System.getProperty("jpackage.app-version")` vyzera, ze sa app to spusta s tymto. minimalne na windows

**Comment by sabomichal** [comment]
manifest vies upravit cez maven-jar-plugin konfiguraciu. Mozes si tam pridat cokolvek potrebujes.

https://maven.apache.org/shared/maven-archiver/index.html

**Comment by jsuchal** [comment]
@kiblik ano api je asi stabilnejsie na taketo ucely. @celuchmarek vies toto kuknut pripadne ako separe PR?
