### ISSUE TITLE
.deb balíček je "príliš moderný", v Debian bullseye sa nenainštaluje

### ISSUE THREAD

**Issue by jurajsarinay** [slovensko-digital/autogram#175]
`# dpkg -i `[`autogram_1.99.9-1_amd64.deb`](https://github.com/slovensko-digital/autogram/releases/download/v1.99.9/autogram_1.99.9-1_amd64.deb)
```text
dpkg-deb: error: archive 'autogram_1.99.9-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive autogram_1.99.9-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 autogram_1.99.9-1_amd64.deb
```

(p. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664)

Ak to skompilujem ručne, `autogram-1.0.0.jar` na bullseye spustiť viem, snáď sa preto oplatí podporovať inštaláciu i na "starších" systémoch.

**Comment by jsuchal** [comment]
Vyzera, ze toto robi jpackage avsak neviem najst nikde, ze by sa mu dal podhodit parameter (napr. na inu kompresiu) pre dpkg-deb cize toto bude tazsie. 

Je tu moznost ten .deb artefakt "prebalit" (prekompripovat).
