### ISSUE TITLE
Logo autogram

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#176]
Je tu dizajnerska uloha - potrebujeme logo pre autogram. Nejake koncept navrhy su tu:

prvy napad od @jsuchal 

![image](https://user-images.githubusercontent.com/26342/236665750-5b70ab5d-69a0-4f62-b7cb-70c0d2c5095a.png)

(Predstavuje tu ciaru dole na ktoru sa bezne podpisuju ludia)

od @pomali 
![image](https://user-images.githubusercontent.com/26342/236665687-39b43606-bd09-4d60-80d9-00ae4ca90698.png)

**Comment by celuchmarek** [comment]
@jsuchal Toto je podľa mňa už hotová vec. Už by som logo nemenil.
