### ISSUE TITLE
Spravanie pri zatvarani okna na MacOS

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#178]
Priatelia jablckari tuto potrebujeme pomoct.

Momentalne sa Autogram pri kliknuti na close (x) zavrie a vypne. Ukazalo sa, ze toto nie je vo svete MacOS standardne spravanie. Ocakava sa, ze app dalej bezi, len je "minimalizovana". Naopak pri Linux a Win je kliknutie na close (x) prikaz na zastavenie aplikacie.

V principe by fix mohol byt hnusny platform dependent switch, ale asi trivialny. Kliknutie na close v hlavnom okne na mac proste bude znamenat minimalizaciu. Pripadne sa spytame, ze ci chce naozaj zavriet Autogram.

Napady?

PS. Pre podpisovacie okna by som nechal spravanie, ze close zrusi podpisovanie (neda sa k nemu vratit) - je to proste "podpisovanie", ktore si zavrel. Tam to je ocakavane.

**Comment by pomali** [comment]
toto vieme vyriesit, ale bolo by pre to potrebne 
- dorobit menu bar (napr cez https://github.com/codecentric/NSMenuFX)
- vyriesit problem, ze ked sa zatvori okno (bez zatvorenia appky) nefunguje Quit z menubar ani z dock-u
- dorobit opatovne spusanie main okna (a zabezpecit aby bolo iba jedno?)

vsetko je urobitelne, ale mne ako MacOS userovi terajsie spravanie nevadi (aj ked ja som asi biased)

**Comment by jsuchal** [comment]
To repo (aj novy fork) vyzeraju uplne mrtvo. 

Nateraz toto nechajme otvorene, ale zatial mame report len od jedneho jablckara, ze to je problem.

**Comment by durkovic** [comment]
Spravanie aplikacii je rozne. Napr. tieto appky su sucastou zakladneho MacOS a po kliknuti na X sa zatvoria: AppStore, Calculator, Contacts, Photos, Settings...

Vzhladom na to, ze na eID kartu mozno otvorit iba jedno spojenie, urcite by som preferoval sucasne spravanie, t.j. zatvorenie appky. To iste robi aj podpisuj.sk

**Comment by jsuchal** [comment]
Ja by som toto asi zavrel, lebo zatial sa to neprejavuje ako problem. Bavil som sa s viacerymi jablckarmi a nebol problem.
