### ISSUE TITLE
Neviem co znamena tlacitko "zmenit" 

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#179]
Pri podpisovani nie je (vraj) zrejme, co sa stane ked kliknem na tlacitko "zmenit". 
![image](https://github.com/slovensko-digital/autogram/assets/26342/1358be1b-ef88-4d32-9156-7e823d3aa2d0)

Nemam na toto silny nazor, ale "zmenit podpisovy certifikat" je uz pomerne dlhe. UXaci pomoc.

**Comment by jsuchal** [comment]
Toto sa vsak udeje az ked clovek klikne v prvom kroku na "Vybrat podpisovy certifikat", cize nejaky kontext by ten clovek mat mohol.
![image](https://github.com/slovensko-digital/autogram/assets/26342/36bf812e-2d7d-4551-bff1-0ea5d7a3c2af)

**Comment by celuchmarek** [comment]
@jsuchal zmenili sme flow. Teraz je tam "podpísať iným certifikátom". Takže podľa mňa je toto done.

**Comment by jsuchal** [comment]
Vyriešil nový flow.
