### ISSUE TITLE
Padne ak je port obsadeny

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/autogram#201]
Ak bezi iny Autogram proces tak pri spusteni spadne (kvoli obsadenemu portu), mohli by sme dat aspon hlasku o tom co sa stalo.

**Comment by tomas-vajs** [comment]
Assigned

**Comment by celuchmarek** [comment]
Vo verzii v2.2.2 už handlujeme chyby pri spustení aspoň error hláškou.
