### ISSUE TITLE
Swagger volá iba port 37200

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/autogram#220]
Swagger by mal vedieť volať port, na ktorom beží Autogram (na ktorom beží aj samotný swagger). Teraz je tam napevno 37200, čo je default port pre Autogram, no dá sa spustiť hocikde.

**Comment by jsuchal** [comment]
Toto sa snazi riesit @pomali, ale neviem ci ideme dobrou cestou. Mozno ma zmysel, ze ked sa serviruje swagger z localhost info endpointu to zmenit podla portu takto. https://stackoverflow.com/questions/66333051/change-swagger-host-and-port-serving-it-statically cc @pomali

**Comment by pomali** [comment]
myslim si, ze toto je skoro neriesitelny problem - chceme aby to fungovalo staticky [1](https://github.com/slovensko-digital/autogram/pull/225#discussion_r1267959022)  a zaroven aby to malo dynamicky port

vieme urobit, ze bude viacero moznosti `localhost:37200` (funguje ked mas default port a swagger je hocikde) a `/` (funguje ked sagger je na /docs)

ale nevieme urobit aby ked si remote cez link na staticky github file mal nastaveny spravny custom port

este vieme urobit nejaky replace na 37200 ked servujeme ten file z /docs, ale stale to nebude fungovat ked mas spusteny barsaky port a pozeras to cez swagger.io

**Comment by celuchmarek** [comment]
podľa mňa tam dajme tie dve možnosti (localhost:37200 a /). Viac by som to nekomplikoval. Že niekto bude z online swaggeru volať Autogram examples na custom porte, to je podľa mňa už nepodstatný edgecase.

**Comment by jsuchal** [comment]
@pomali zapracuj toto do PR a mergneme aj to

**Comment by pomali** [comment]
zapracovane
