### ISSUE TITLE
Podpisovanie CAdES

### ISSUE THREAD

**Issue by Slaaavo** [slovensko-digital/autogram#229]
Bolo by super, keby som si vedel v autograme vybrat, aby mi pdf aj zabalilo do .asice kontajnera a podpisalo CAdES.

**Comment by jsuchal** [comment]
@Slaaavo ahoj, zaujimava poziadavka - na co toto potrebujes? Ono to cez API mozne je, ale cez GUI nie - kedze nasa skusenost je, ze ludia .asice moc nepoznaju a nevedia co s tym robit.

**Comment by Slaaavo** [comment]
No, dnes som podpisoval nejaké dokumenty pri zakladaní firmy a bola tam požiadavka, že to nemôže byť pdf a pades, ale že to musí byť asice a cades, lebo že to úrady vyžadujú. Tak som to spravil cez nejakú webovú službu, čo odporúčali.

**Comment by celuchmarek** [comment]
Práve sme mergli #262, čo prináša možnosť podpisu PDF ako PAdES, XAdES ASiC-E alebo CAdES ASiC-E cez nastavenia v desktop móde a --pdf-level flag v CLI móde.
