### ISSUE TITLE
Podpisovanie zaheslovaných PDF

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/autogram#230]
Viem si predstaviť usecase, že chcem podísať zaheslované PDF. Momentálne to nič neukáže ani nepovie. Možno to niekde spapá error.

![image](https://github.com/slovensko-digital/autogram/assets/12500066/2698d4cb-2b10-474f-a31e-b125ce7a7a54)

**Comment by celuchmarek** [comment]
Rozmýšľam, aký je vlastne usecase. Všeobecne podpis by mal byť v podstate vždy public, neviem si predstaviť situáciu, kedy by si chcel mať podpis až za heslom. Na druhej strane si viem predstaviť, že máš podpísané pdf a vieš, že je podpísané, ale obsah si vieš pozrieť až s heslom, lebo je v ňom niečo private.

Tým pádom nechceš zaheslovať podpísaný súbor s podpisom, lebo ten podpis by si bez hesla tiež nevidel. Ale právaže dáva zmysel, že podpíšeš zaheslovaný súbor. Čiže takto by som postupoval. Možno ešte vieš skúsiť zistiť, ako sa to niekde používa, ale toto mi dáva zmysel.

A odheslované podľa mňa nie je ok.

**Comment by pomali** [comment]
@jsuchal mas na to nejaky nazor? urobime to tak, ze zaheslovane pdf si vies pozriet a potom sa podpise ako asice?

**Comment by jsuchal** [comment]
Ja by som vyhodil chybu, ze to je zaheslovane a nepodporujeme. (zatial)
