### ISSUE TITLE
Release v1.99.15

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#239]
## Windows

- [x] funguje inštalácia na Windows cez stiahnutý .msi
- [x] funguje spustenie v GUI móde
- [x] funguje URL handler [autogram://go](autogram://go)
- [x] funguje GUI otvoriť jeden súbor, ten sa zobrazí, viem ho podpísať, vytvorí sa podpísaný súbor
- [ ]  funguje CLI `autogram --help`

## Linux
- [x] funguje inštalácia na Linux (Debian-based) cez stiahnutý .deb
- [x] funguje inštalácia na Linux cez stiahnutý .rpm
- [x] funguje spustenie v GUI móde
- [x] funguje URL handler [autogram://go](autogram://go)
- [x] funguje GUI otvoriť jeden súbor, ten sa zobrazí, viem ho podpísať, vytvorí sa podpísaný súbor
- [x]  funguje CLI `autogram --help`

## MacOS
- [x] funguje inštalácia na MacOS cez stiahnutý .pkg
- [x] funguje spustenie v GUI móde
- [x] funguje URL handler [autogram://go](autogram://go)
- [x] funguje GUI otvoriť jeden súbor, ten sa zobrazí, viem ho podpísať, vytvorí sa podpísaný súbor
- [x] funguje CLI `/Applications/Autogram.app/Contents/MacOS/AutogramApp --help`

## Na aspoň jednom systéme

- [x] fungujú všetky smoke testy `./mvnw test -Psmoke`
- [x] funguje spustenie v GUI serverovom móde `autogram --url=autogram://listen?protocol=http&port=37201` na inom porte
- [x] funguje CLI `autogram --cli --source source.pdf`
- [x] funguje CLI `autogram --cli --source source.pdf --target target.pdf`
- [x] funguje CLI `autogram --cli --source source-dir --target target-dir`
- [x] funguje API info request
- [x] funguje API docs request
- [x] funguje API sign request
- [x] funguje s [extension](https://github.com/slovensko-digital/autogram-extension)

**Comment by pomali** [comment]
Overil som ze:

MacOS
- funguje inštalácia na MacOS cez stiahnutý .pkg
- funguje spustenie v GUI móde
- funguje URL handler autogram://go
- funguje GUI otvoriť jeden súbor, ten sa zobrazí, viem ho podpísať, vytvorí sa podpísaný súbor
- funguje CLI /Applications/Autogram.app/Contents/MacOS/AutogramApp --help

Na aspoň jednom systéme
- fungujú všetky smoke testy ./mvnw test -Psmoke
- funguje spustenie v GUI serverovom móde autogram --url=autogram://listen?protocol=http&port=37201 na inom porte
- funguje CLI autogram --cli --source source.pdf
- funguje CLI autogram --cli --source source.pdf --target target.pdf
- funguje CLI autogram --cli --source source-dir --target target-dir

**Comment by jsuchal** [comment]
Ja som skusil s extension teraz realne podanie a prejde. Ale 2x mi to zmrzlo pri vybere certifikatu - co sa mi predtym nedialo. Neviem cim to je. (eid klient spusteny + prihlasoval som sa cez eid)

**Comment by jsuchal** [comment]
@pomali vyklikal som tie tvoje hore.

**Comment by celuchmarek** [comment]
Ja som skúsil s extension niečo podpísať a mám pocit, že mi to funguje rovnako ako predtým. Inak na Windows to viete niekto otestovať?

**Comment by jsuchal** [comment]
@luciajanikova ?

**Comment by celuchmarek** [comment]
Ja som nainštaloval .rpm na Ubuntu cez Alien, čo nie je natívne, ale teda funguje to, tak odklikávam, keďže package je zjavne ok.

**Comment by jsuchal** [comment]
Ideme znova 1.99.16
