### ISSUE TITLE
Dlhy nazov vystupneho priecinku sa zobrazuje zle

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/autogram#241]
signing success dialog - hyperlink sa nezalamuje tym padom sa success dialog rozbije

https://slovensko-digital.slack.com/archives/C0564RNLT62/p1691051575593389

**Comment by pomali** [comment]
predtym neboli take dlhe nazvy (vracal sa iba nazov suboru)

myslim ze sa to da rozbit na viacero hyperlinkov

**Comment by jsuchal** [comment]
Nespravime nejaky truncate co tam da zaciatok ... koniec a zabezpeci ze to nebude dlhsie ako N znakov?

**Comment by pomali** [comment]
ak mas pocit, ze to pouzivatelia pochopia tak je to najlahsie

druha moznost je to rozbit na viacero hyperlinkov podla `/`

**Comment by jsuchal** [comment]
Ok skus to rozbit podla / alebo \ (na win) a uvidime co to spravi.
