### ISSUE TITLE
Pokazeny encoding na Win

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/autogram#249]
![image](https://github.com/slovensko-digital/autogram/assets/1194439/5139de4c-07e6-4a49-9224-6e25431cc719)

pri spusteni swagger example-u
![image](https://github.com/slovensko-digital/autogram/assets/1194439/39219c51-cad1-4e05-862d-ced3b2c5177c)

**Comment by pomali** [comment]
takisto 
![image](https://github.com/slovensko-digital/autogram/assets/1194439/a97bb77a-e2a4-4684-9ce5-43aa5a0cdb3f)
![image](https://github.com/slovensko-digital/autogram/assets/1194439/4d2e6e3a-d900-4005-bbaf-c539d22e0ab2)

**Comment by pomali** [comment]
ale iba ak to spustam cez IDE

**Comment by jsuchal** [comment]
Toto je aktualny main alebo nieco ine? Lebo encodingy fixoval @sabomichal ak si spravne spominam.

**Comment by pomali** [comment]
ano, aktualny main

**Comment by celuchmarek** [comment]
Som na 95% presvedčený, že toto sme už vyriešili. Náhodou, @pomali, nevieš to zreplikovať? Mne to túto chybu nerobí, takže za mňa ok.

**Comment by pomali** [comment]
Tiež to mám ok
