### ISSUE TITLE
Instalovane/package verzie su pomalsie

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#277]
Nainstalovana verzia ide vyrazne (u mna 2x) pomalsie ako pri pustani z IDEA pri vyvoji. Je to velmi zvlastne a citit to najma v pripade, ked sa spusti Autogram a hned das overit nejaky dokument. 

Najblizsie tomuto som nasiel https://stackoverflow.com/questions/69125163/java-application-runs-much-slower-when-packaged-as-a-macos-app 

Na linuxe s .deb to iste. 

Nainstalovana verzia 
[Screencast from 2023-09-29 16-11-48.webm](https://github.com/slovensko-digital/autogram/assets/26342/dd98627e-24a5-4968-894e-ce5d2d196739)

vs

"vyvojova verzia"
[Screencast from 2023-09-29 16-13-38.webm](https://github.com/slovensko-digital/autogram/assets/26342/e964616f-7ad2-4608-bc03-10b3580776b6)

**Comment by jsuchal** [comment]
@1azyman alebo @sabomichal nejake napady?

**Comment by sabomichal** [comment]
Prekvapilo by ma to, ak by to tak bolo, ale podozrivym moze byt ten osekany typ JRE (client, minimal), ktory sa v balickovanej verzii pouziva (mensia velkost balicka).

**Comment by celuchmarek** [comment]
Haluz. Spravil som si build bez tých minimal options a ide mi to potom rovnako rýchlo ako v dev. Takže zjavne to je tým.

**Comment by jsuchal** [comment]
Vyborne tak to teda revertnime.
