### ISSUE TITLE
Ako sa dostanem do nastaveni?

### ISSUE THREAD

**Issue by Slaaavo** [slovensko-digital/autogram#304]
Na MR komentaroch vidim, ze su tu nejake nastavenia, kde si mozem nastavit typ podpisu, ale neviem, ako sa do nich dostanem. Mam najnovsiu verziu.
![image](https://github.com/slovensko-digital/autogram/assets/10650591/79f3fe0e-8638-4b35-af55-61cd6d0ade1e)

**Comment by celuchmarek** [comment]
V päte na prvej obrazovke je link "Nastavenia" hneď vedľa "O Autograme" :thinking: Ak to tam nemáš, daj, prosím, vedieť, čo máš za OS.
![image](https://github.com/slovensko-digital/autogram/assets/12500066/8d560728-0f2e-46de-9eba-355e2b9c278e)

**Comment by celuchmarek** [comment]
Ahoj. Nastavenia už máme v main vetve, ale ešte sa nestihli dostať do posledného releasu.

**Comment by Slaaavo** [comment]
Ja vidim len toto. Mam WIndows 11
![image](https://github.com/slovensko-digital/autogram/assets/10650591/dbdec9b9-67b7-4def-b273-8b133a3b42a8)

**Comment by Slaaavo** [comment]
A kedy to bude releasnute?

**Comment by jsuchal** [comment]
@celuchmarek pre release asi vieme spraviť aj hneď. Ďalší veľký release bude asi až keď dáme vizualizáciu xml dokumentov.

**Comment by celuchmarek** [comment]
@Slaaavo spravili sme pre-release s nastaveniami: https://github.com/slovensko-digital/autogram/releases/tag/v1.99.23
