### ISSUE TITLE
PDF/A-1 

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#343]
> PDF/A-1 je cista katastrofa, podporuje to iba najzakladnejsie veci z PDF specifikacie spred ~20 rokov, takze dnes bezny PDF dokument nemusi byt vobec mozne skonvertovat do PDF/A-1 bez toho, aby sa stratili nejake features. Tento format treba definitivne opustit, nevyzaduju ho uz ani platne standardy.

Minimalna pouzitelna uroven pre dnesnu dobu je PDF/A-2, a ak v dokumente nie su veci pre accessibilitu, musi to byt PDF/A-2B.

_Originally posted by @durkovic in https://github.com/slovensko-digital/autogram/issues/263#issuecomment-1827984885_

**Comment by jsuchal** [comment]
prave taketo informacie o PDF/A su pre bezneho pouzivatela uplna sifrovacka. Ani ja by som asi nevedel co mam s touto informaciou urobit. Co znamena ta zelena fajka? A kedy tam nebude? Ked tam dame stare PDF ako zistime ci tam su animacie atd...?

Vies poslat nejake ukazkove pdf co overi CEP v pohode (ak vobec mozeme ho brat ako referencny) a nejake co nezoberie CEP v pohode? (Myslim, tie stare formaty, pre PDF/A-1A 2A 2B asi vieme co treba robit - nic nezobrazovat.

**Comment by durkovic** [comment]
No, PDF s vlozenym videom som na CEP este poslat neskusal, vsetko bezne mi zatial preslo.
Taky Word for MAC totiz nema volbu Save as PDF/A, takze by bola potrebna externa konverzia.

Povedal by som, ze bezny pouzivatel toto dnes vobec nemusi riesit, preto sa mi to vyskakovacie okno (Pozor, show stopper!) zda byt prehnane.

Zelena fajka znamena, ze PDF preslo validaciou archivneho formatu. Moze sa totiz stat, ze subor formalne deklaruje napr. PDF/A-2B, ale neobsahuje potrebne veci.

**Comment by athelas64** [comment]
Len ako doplňujúca info: Microsoft Office pri zaškrtnutí PDF-A v nastaveniach exportu do PDF jeho vstavaným nástrojom vždy exportoval do PDF/A-1A, ale keď som to teraz overoval, tak už mi to exportovalo do PDF/A-3A, neviem ale, kedy prišlo k zmene, lebo v changelogu to zatiaľ nie je (používam 365, kanál Insider Beta). 

Každopádne, tento problém teda asi časom vyhnije, bežný používateľ medzi verziami PDF/A nerozlišuje.

**Comment by originalmagneto** [comment]
macOS Preview app, pomocou ktorého konvertujem vytvára PDF/A-2B (ISO 19005-2) a v rámci zaručenej konverzie som nemal nikdy problém.

**Comment by jsuchal** [comment]
> nemal nikdy problém.

toto znamena presne co? Niekto to aj kontroloval?

**Comment by originalmagneto** [comment]
> > nemal nikdy problém.
> 
> toto znamena presne co? Niekto to aj kontroloval?

Znamená to, že v rámci zaručenej konverzie to prešlo cez kataster, ako aj cez exekučné, a upomínacie konanie, keďže som to ako advokát konvertoval a podával priamo ja. Interné systémy na kontrolu ZaKo dokumentov jednotlivých inštitúcií nepoznám, ale pevne verím, že v rámci technickej kontroly vykonávajú aj compliance testy formátov dokumentov.

**Comment by celuchmarek** [comment]
Autogram teda overuje súlad s PDF/A (teda 1, 2 a 3). Upravili sme k tomu aj príslušné texty v aplikácii. Túto issue tak zavriem.
