### ISSUE TITLE
Feature Request: Verzia pre Android

### ISSUE THREAD

**Issue by adokitkat** [slovensko-digital/autogram#362]
Dobrý deň,

chcel by som sa spýtať, či niekedy v budúcnosti bude verzia Autogramu skompilovaná pre arm/aarch64 Android telefóny - vyzerá, že kód je v Jave, takže by to nemusel byť až taký problém.

Ďakujem za odpoveď.

**Comment by jsuchal** [comment]
@adokitkat existuje nejaka citacka co by vedela s mobilom fungovat?

**Comment by adokitkat** [comment]
Dobrá otázka :) Nie som si istý...

**Comment by jsuchal** [comment]
Toto si viem predstavit, ze by mohlo fungovat s opensc, lebo teraz je prerekvizita eidklient co na arm/aarch64 neviem ci niekedy bude

**Comment by durkovic** [comment]
Napr. nove eID maju NFC rozhranie, takze citacku netreba.

**Comment by jsuchal** [comment]
@durkovic to je trosku iny vesmir, mozno @jurajsarinay by vedel poradit co treba na to aby sa to nejako dalo zintegrovat.

**Comment by adokitkat** [comment]
@jurajsarinay To som nevedel, parada 👍 Pytal som sa hlavne na ukor mojho otca co by to vyuzil, ja mam notebook vacsinou so sebou takze kludne vyuzijem aplikaciu aj v terajsej podobe 😃 Len este ten novy obciansky vybavit... :)

**Comment by originalmagneto** [comment]
Je toto relevantné? Skôr ale pre iOS / iPadOS.... https://www.macrumors.com/2024/01/20/apple-offers-to-open-nfc-in-europe/

**Comment by jsuchal** [comment]
@originalmagneto skor nie, to bude asi len SDK na platby cez NFC.

**Comment by originalmagneto** [comment]
> @originalmagneto skor nie, to bude asi len SDK na platby cez NFC.

Tak po dnešku sme asi všetci vcelku happy a velmi sa teším na iOS / iPadOS (a tým pádom aj macOS) verziu Autogramu. Rád otestujem (NFC OP si vybavím čo najskôr).

**Comment by jsuchal** [comment]
Takto to nefunguje. To sdk sa s autogramom nedá len tak spojiť, ale niečo vymyslíme. 

Btw to sdk napríklad určite nebude podporovať hromadné podpisovanie.

**Comment by durkovic** [comment]
Hromadne podpisovanie je skor scenar pre firmy a OVM, podla mna vobec nevadi, ak nebude dostupne pre eID.

**Comment by jsuchal** [comment]
@durkovic no praveze je to nieco co sa pouziva. Vsade tam kde to nepodpisuje nejaky mandant ale osoba. Je toho celkom dost.

**Comment by durkovic** [comment]
No, to je ale velmi tenky lad, takyto scenar nikdy nebol pre eID oficialne podporovany.
V klasickej podpisovej knihe vzdy vidim, co podpisujem, tu sa ale dokument vobec nezobrazi.

**Comment by jsuchal** [comment]
@durkovic ten scenar je mierne iny. Ty si vies dokumenty lokalne pripravit a samozrejme dobre skontrolovat :)

**Comment by durkovic** [comment]
Ak si robis vsetko sam, ano. Ale ak dokumenty pripravuje niekto iny a ty len podpisujes, bolo by dobre mat rovnaky standard ako v klasickej podpisovej knihe.

**Comment by originalmagneto** [comment]
> @durkovic ten scenar je mierne iny. Ty si vies dokumenty lokalne pripravit a samozrejme dobre skontrolovat :)

Jano ma pravdu, jednotlivé kontroly a úpravy riešiš keď robíš zaručenú konverziu, ale ostatne autorizácie si pripraví človek dopredu a nedáva zmysel kontrolovať dokumenty ešte raz a po jednom.

**Comment by celuchmarek** [comment]
Túto issue zatváram, keďže svetlo sveta uzrel [Autogram v mobile](https://sluzby.slovensko.digital/autogram-v-mobile/).
