### ISSUE TITLE
Link na novú verziu

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/autogram#363]
Link na novú verziu v update dialógu ukazuje stále na github. Mal by tam byť viac user-friendly link na peknú novú stránku: https://sluzby.slovensko.digital/autogram/

**Comment by xseman** [comment]
Kombinácia linku na stránku + list všetkých artifaktov z posledného release? [Stánka](https://sluzby.slovensko.digital/autogram/#download) na ne ukazuje, tak by to bol o jeden klik menej pre tých ktorý chcú priamo download.

**Comment by jsuchal** [comment]
@xseman myslim, ze zmenit na ten link na download bude stacit.

**Comment by jsuchal** [comment]
@xseman inak toto je dobra issue aj pre hocikoho mimo internych SD ludi. Keby si sa citil na PR tak smelo :)

**Comment by xseman** [comment]
Rád pomôžem, assigni to na mňa.
