### ISSUE TITLE
Nefunguje eID na niektorých Windows 10 systémoch

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/autogram#372]
Na niektorých Windows 10 nevie nájsť Autogram `C:\Program Files (x86)\eID_klient\pkcs11_x64.dll` aj keď tam ten súbor naozaj je. Zatiaľ sa objavilo dvakrát na SK systéme (idk, či to môže mať vplyv).

**Comment by jsuchal** [comment]
Nejaky workaround mame ci nie?

**Comment by celuchmarek** [comment]
Nie

**Comment by celuchmarek** [comment]
K tomuto mám ďalšie zistenia. `DefaultDriverDetector.java` pri hľadaní driverov pri volaní `TokenDriver::isInstalled` nad eID vráti True. Volá sa tam `path.toFile().exists()` a všetko je ok. Ale následne pri podpisovaní to padne na `token.getKeys()` s chybou `Caused by: java.io.IOException: The specified module could not be found. C:\Program Files (x86)\eID_klient\pkcs11_x64.dll`.

Išiel som debugovať, tak som na windows nainštaloval IntelliJ, aby som to vedel spustiť v debug móde. Chcel som spustiť `./mvnw initialize`, tak som doinštaloval do systému aj globálne Liberica JDK 17. Následne som opäť zavolal `./mvnw initialize` a spustil debug. Zázračne podpis fungoval ok, nebol problém s prístupom k súboru.

Spustil som teda opäť nainštalovaný Autogram v2.1.2. A hľa, normálne vypýtal BOK a PIN a podpísal som. Takže zjavne inštaláciou IntelliJ alebo JDK 17 sa problém vyriešil a neviem čo s tým ďalej.

**Comment by jsuchal** [comment]
Mozno relevantne https://bugs.openjdk.org/browse/JDK-8077138

**Comment by celuchmarek** [comment]
Chyba je v tom, že na Win môžú chýbať nejaké dll dependencies pre pre pkcs. Riešením je doinštalovať Visual C++ Redistributable for Visual Studio 2015 napr: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by celuchmarek** [comment]
Ukázalo sa teda, že chyba je skôr nie u nás a treba doinštalovať tie VC redist. Pridali sme k tomu hlášku do Autogramu. Zatváram.
