### ISSUE TITLE
Identifikovať aj súbory s .PDF (uppercase) príponou ako PDF dokumenty

### ISSUE THREAD

**Issue by nekromoff** [slovensko-digital/autogram#396]
Skúsil som naraz viacero PDFiek, následne samostatne jedno PDF.
![image](https://github.com/slovensko-digital/autogram/assets/8550349/8781c604-49c5-4c46-bf17-c31af1ff3282)

Napriek nastaveniu my to generuje ASICE namiesto PDF.

v2.1.5 DEB balík

**Comment by nekromoff** [comment]
![image](https://github.com/slovensko-digital/autogram/assets/8550349/23583b87-0dcf-437d-84cd-39b754195a6d)

**Comment by nekromoff** [comment]
Ano, oba pripady som skusil. Myslel som, ze mozno blbne hromadne, ale potom aj individuálne.

**Comment by celuchmarek** [comment]
@nekromoff ešte mi napadá, či má podpisovaný súbor príponu `.pdf` Videl som už aj od štátu nejaké PDF, ktoré prišli bez prípony a podobne. Autogram určuje v tomto stand-alone móde typ súboru iba podľa `.pdf`

**Comment by nekromoff** [comment]
je to uplne klasicke PDF, nie je od "statu" :-)

**Comment by nekromoff** [comment]
export z google docs ako PDF

**Comment by nekromoff** [comment]
mozem poslat log, ak to niekde loguje na pozadi

**Comment by nekromoff** [comment]
![image](https://github.com/slovensko-digital/autogram/assets/8550349/b29a72d1-cff4-43e5-b2de-f9bf615f28e2)

**Comment by celuchmarek** [comment]
Problém spôsobuje tá prípona, ako som spomínal. `.PDF` nie je `.pdf`. Aj podľa https://www.iana.org/assignments/media-types/application/pdf je pre PDF dokumenty asociovaná iba prípona `.pdf`. Avšak, asi vieme zaradiť feature request, aby Autogram okrem `.pdf` detegoval aj `.PDF`.

**Comment by nekromoff** [comment]
To by bolo fajn.

IANA je jedna vec, druha vec je realita a UX. Je naivne sa domnievat, ze
pdf subory budu vzdy ako .pdf a nie ako .PDF. Na tomto padali mnohe webove
sluzby, ktore umoznovali upload obrazkov, ale v lowercase .jpg a pod., pri
JPG to neukazalo na disku nic.

To su take tie memecka, ze falsehoods programmers believe about filenames
atd.

**Comment by celuchmarek** [comment]
@GeorgiyGit
