### ISSUE TITLE
Nesulad informacii o casovych peciatkach

### ISSUE THREAD

**Issue by durkovic** [slovensko-digital/autogram#412]
Pri overovani prilozeneho suboru z madarskeho eGOV-u Autogram v sumare nespravne vypise "Neznama CP", ale v detailoch je spravne "Kvalifikovana CP".
[keaesz_jelentes_20240207_071323.pdf](https://github.com/slovensko-digital/autogram/files/14603639/keaesz_jelentes_20240207_071323.pdf)

**Comment by celuchmarek** [comment]
@durkovic v najnovšej verzii v2.2.2 je toto už fixnuté, vieš potvrdiť?

**Comment by md24245** [comment]
Ano, je to OK.
