### ISSUE TITLE
Lepšia error hláška pri odstávke slovensko.sk

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/autogram#417]
Keď prebieha odstávka slovensko.sk, nefunguje ani URL na resourcy elektronických formulárov. Momentálne to hodí takúto hlášku:
<img width="562" alt="Snímka obrazovky 2024-04-13 o 20 36 38" src="https://github.com/slovensko-digital/autogram/assets/12500066/98f0fc1e-a8ee-429d-a5da-7571679b9a3e">

Chyba nastane v `digital/slovensko/autogram/core/eforms/EFormResources.java::findResources`, keď sa zavolá `var parsed_manifest_xml = getXmlFromDocument(new InMemoryDocument(manifest_xml, "manifest.xml"));`, pretože v `mainfest_xml` je toto:
```
 <!DOCTYPE html>
<html>

<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Nedostupnosť portálu</title>
...
```

**Comment by xHyroM** [comment]
Celkom sranda, že nevracajú ani iný status kód než 200 ;)

**Comment by xHyroM** [comment]
> A ako vieme, ze posielaju 200?

Predpokladám to, keďže `URLConnection#getInputStream` vyhodí v prípade iného kódu než 200 exception. Včera som mal možnosť to otestovať, ale nenapadlo mi to.

**Comment by celuchmarek** [comment]
Jj, vracajú 200, keďže, ako píše xHyroM, nepadá to na nie-200 errore.
