### ISSUE TITLE
Odchytiť exception pri spustení Autogramu

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/autogram#431]
Dostávame hlásenia, že na niektorých systémoch (zväčša Win 10 a 11) sa Autogram "nedá spustiť". Niekedy to hodí taký malý error dialóg: "Failed to launch JVM".

Jeden z problémov, ktoré sme už kedysi vyriešili, bol ten, že sa nedali načítať hodnoty UserSettings, lebo v registry bola hodnota, ktorá sa nedala sparsovať.

Toto by sme mohli všobecne vyriešiť tým, že hneď úplne na začiatku spustenia Autogramu odchytíme hociakú chybu (keďže nevieme, čo všetko sa môže pokaziť na všetkých systémoch) a túto chybu nejako rozumne ukážeme userovi, aby nám vedeli napísať email a aby sme my mohli zdebugovať.

Niečo súvisiace je rozrobené v #292 .

**Comment by athelas64** [comment]
Ono to píše na Win  ak Autogram už beží a človek ho spustí znovu. Spustí sa druhá inštancia, ktorá do pár sekúnd spadne a vyhodí Failed to launch JVM - asi preto, že už raz beží a nemôže 2x

**Comment by matesfila** [comment]
úloha in progress v rámci hackday

**Comment by matesfila** [comment]
vytvorený pull request
https://github.com/slovensko-digital/autogram/pull/434
