### ISSUE TITLE
Rodné číslo v sériovom čísle certifikátu

### ISSUE THREAD

**Issue by Bjelko** [slovensko-digital/autogram#453]
Ono to nie je problem len Autogramu.   Podpíšem pdf, dám si overiť a v detailoch je rodné číslo PNSK-..... Cez Autogram je to ako neviditeľný podpis, ale Acrobat reader ak vložím certifikovaný podpis s jednoznačným menom tak vidno s PNSK... to sa dá vytlačiť....
Je to normálne?

**Comment by celuchmarek** [comment]
Zdravím. Áno, je to normálne. Ide o to, že na Slovensku je to vymyslené tak, že v kvalifikovanom podpisovom certifikáte fyzických osôb je uložené aj rodné číslo, zrejme pre jednoduchú identifikáciu podpisujúceho.

Podpisovače ani softvér na zobrazovanie s tým nemajú vlastne nič - oni len použijú/zobrazia to, čo je v certifikáte.
