### ISSUE TITLE
Nefunguje right click > Copy v dialógu s neočakávanou chybou

### ISSUE THREAD

**Issue by jozefizso** [slovensko-digital/autogram#482]
V dialógu Neočakávaná chyba rozbalím detail chyby, označím text a kliknem pravým tlačidlom. V kontextovom menu vyberiem Copy. Táto funkcia nič nespraví a označený text nie je skopírovaný do schránky.

Kontextové menu je zle naštýlované a nezobrazuje sa správne.

![image](https://github.com/slovensko-digital/autogram/assets/287778/ca6e3862-c305-43b3-ab86-70be7de5f475)

**Comment by celuchmarek** [comment]
Vďaka. Toto bude asi ťažšie na opravu - bude treba sa pohrabať v JavaFX a zistiť, kde je problém. Ale teda zaradíme ako bug a uvidíme.

**Comment by xhyrom** [comment]
Nedarí sa mi to reprodukovať, na linuxe (wayland) sa mi v pohode skopíruje text do schránky, len to nemá dobrý štýl
