### ISSUE TITLE
Neuznané podpísy v .asice súboroch na slovensko.sk

### ISSUE THREAD

**Issue by alexsk** [slovensko-digital/autogram#483]
Súbory .asice vytvorené vo verzii 2.2.2 nie sú rozpoznané ako podpísané v elektronickej schránke slovensko.sk
![image](https://github.com/slovensko-digital/autogram/assets/951802/811b7139-e990-4678-8153-cd7302dddaa0)

**Comment by celuchmarek** [comment]
@alexsk vieš vyskúšať, že pri podpise priamo na portáli cez extension "Autogram na štátnych weboch" je podpis v poriadku?

**Comment by alexsk** [comment]
Áno, podpis cez extension "Autogram na štátnych weboch" ide v poriadku, bez žiadnych chyb.

Problém sa týka len súborov vytvorených manuálne prostredníctvom aplikácie Autogram a nahraných na portál slovensko.sk

**Comment by celuchmarek** [comment]
@alexsk v najnovšej latest verzi v2.2.3 je to opravené: https://sluzby.slovensko.digital/autogram/#download
