### ISSUE TITLE
Flow popisovanie - neviem co mam robit

### ISSUE THREAD

**Issue by alhafoudh** [slovensko-digital/autogram#64]
Ked dam podpisovat dokument, tak laika nemusi napadnut, ze ma kliknut na "nacitat cerifikaty".
Mohlo by bolo dobre rovno ich rovno requestnut z karty, ale chapem ze chceme dat asi moznost uzivatelovi prestudovat si co vlastne ide podpisovat.
Mozno staci premenovat tlacidlo na nieco ako "Zacat podpisovanie".

**Comment by celuchmarek** [comment]
@jsuchal toto asi môžeme zavrieť s novým flowom, nie?
