### ISSUE TITLE
Release proces je divny

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/autogram#83]
Momentalne je GH action release proces naviazany na push, co je mega divne, malo by sa to odpalit na event tagnutia verzie. mvn command by sa mal pustit rovnaky aj s testami. 

Bezny CI proces by nemal robit packaging (si myslim), ale len zbehnut testy a skusit build.

**Comment by jsuchal** [comment]
@celuchmarek a @sabomichal pofixoval som toto. package workflow (build) sa pusta len ak sa pushne tag a testy sa pustaju cez `./mvnw test` - musel som to jococomo prehodit do test phase v pom.xml (neviem ci to je standard @sabomichal)

V kazdom pripade toto uz vie otestovat aj PR.

**Comment by jsuchal** [comment]
Este to uplne testy na PR nepusta asi kvoli nejakej bezpecnosti.

**Comment by sabomichal** [comment]
Dal si ich myslim pustat len na push, nie na PR podla aktualneho CI/CD wf.
